#!/bin/sh

. ../../setup_guile_test_env

# 1st argument is absolute path to hand coded guile source directory
# 2nd argument is absolute path to component C++ shared library build directory
# 3nd argument is absolute path to component SWIG build directory

add_local_paths \
    . \
    /home/ecandeia/Projetos/RadioCognitivo/Gnuradio/gnuradio/gr-vocoder/swig \
    /home/ecandeia/Projetos/RadioCognitivo/Gnuradio/gnuradio/gr-vocoder/swig

/usr/bin/guile -e main -c '(use-modules (gnuradio test-suite guile-test))' -t .
